on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    # tags:
    #   - "*"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run script
      run: ci/ci_ubuntu.sh
    - name: Upload
      # if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v3
      with:
        name: plugins_ubuntu
        path: plugins_ubuntu

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run script
        run: ci/ci_windows.ps1
      - name: Upload
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v3
        with:
          name: plugins_windows
          path: plugins_windows

  build-macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run script
        run: ci/ci_macOS.sh
      - name: Upload
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v3
        with:
          name: plugins_macOS
          path: plugins_macOS
