on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run script
      run: ci/ci_ubuntu.sh
    - name: Upload
      # if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: plugins_ubuntu
        path: plugins_ubuntu

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run script
        run: ci/ci_windows.ps1
      - name: Upload
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: plugins_windows
          path: plugins_windows

  build-macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run script
        run: ci/ci_macOS.sh
      - name: Upload
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: plugins_macOS
          path: plugins_macOS

  release-packaging:
    needs: [build-ubuntu, build-windows, build-macOS]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/UhhyouPluginsJuce') }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Run package script
        run: |
          tree -an
          zip -r UhhyouPluginsJuce.zip plugins_*
      - name: Get Release Notes
        run: 'echo "$(git tag -l --format="%(contents:body)" $GITHUB_REF_NAME)" > RELEASE_NOTES'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES
          files: UhhyouPluginsJuce.zip
