on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "*"

env:
  package_path: UhhyouPluginsJuce_plugins

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.set-matrix.outputs.plugins }}
    steps:
      - uses: actions/checkout@v6
      - name: Generate Matrix from Directories
        id: set-matrix
        run: |
          python -c '
          import os, json
          plugins = []
          for folder in ["plugin", "experimental"]:
              if os.path.exists(folder):
                  plugins.extend([d for d in os.listdir(folder) if os.path.isdir(os.path.join(folder, d)) and not d.startswith(".")])
          print(f"plugins={json.dumps(plugins)}")
          ' >> $GITHUB_OUTPUT

  build-ubuntu:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJSON(needs.setup-matrix.outputs.plugins) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Run script
      run: ci/ci_ubuntu.sh ${{ matrix.plugin }}
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: plugins_ubuntu_${{ matrix.plugin }}
        path: plugins_ubuntu

  build-windows:
    needs: setup-matrix
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJSON(needs.setup-matrix.outputs.plugins) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Run script
        run: ci/ci_windows.ps1 -Plugin ${{ matrix.plugin }}
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: plugins_windows_${{ matrix.plugin }}
          path: plugins_windows

  build-macOS:
    needs: setup-matrix
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJSON(needs.setup-matrix.outputs.plugins) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Run script
        run: ci/ci_macOS.sh ${{ matrix.plugin }}
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: plugins_macOS_${{ matrix.plugin }}
          path: plugins_macOS

  release-packaging:
    needs: [build-ubuntu, build-windows, build-macOS]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/UhhyouPluginsJuce') }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: ${{ env.package_path }}
          pattern: plugins_*
          merge-multiple: true
      - name: Run package script
        run: |
          tree -an
          zip -r UhhyouPluginsJuce.zip ${{ env.package_path }}
      - name: Get Release Notes
        run: 'echo "$(git tag -l --format="%(contents:body)" $GITHUB_REF_NAME)" > RELEASE_NOTES'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
            UhhyouPluginsJuce.zip \
            --title "$GITHUB_REF_NAME" \
            --notes-file RELEASE_NOTES
